namespace Pax360.Helpers
{
    public class StaticHelpers
    {
        public static int CityList(string isim)
        {
            List<City> cities = new List<City>
        {
            new City { Plaka = 1, Isim = "Adana" },
            new City { Plaka = 2, Isim = "Adıyaman" },
            new City { Plaka = 3, Isim = "Afyonkarahisar" },
            new City { Plaka = 4, Isim = "Ağrı" },
            new City { Plaka = 5, Isim = "Amasya" },
            new City { Plaka = 6, Isim = "Ankara" },
            new City { Plaka = 7, Isim = "Antalya" },
            new City { Plaka = 8, Isim = "Artvin" },
            new City { Plaka = 9, Isim = "Aydın" },
            new City { Plaka = 10, Isim = "Balıkesir" },
            new City { Plaka = 11, Isim = "Bilecik" },
            new City { Plaka = 12, Isim = "Bingöl" },
            new City { Plaka = 13, Isim = "Bitlis" },
            new City { Plaka = 14, Isim = "Bolu" },
            new City { Plaka = 15, Isim = "Burdur" },
            new City { Plaka = 16, Isim = "Bursa" },
            new City { Plaka = 17, Isim = "Çanakkale" },
            new City { Plaka = 18, Isim = "Çankırı" },
            new City { Plaka = 19, Isim = "Çorum" },
            new City { Plaka = 20, Isim = "Denizli" },
            new City { Plaka = 21, Isim = "Diyarbakır" },
            new City { Plaka = 22, Isim = "Edirne" },
            new City { Plaka = 23, Isim = "Elazığ" },
            new City { Plaka = 24, Isim = "Erzincan" },
            new City { Plaka = 25, Isim = "Erzurum" },
            new City { Plaka = 26, Isim = "Eskişehir" },
            new City { Plaka = 27, Isim = "Gaziantep" },
            new City { Plaka = 28, Isim = "Giresun" },
            new City { Plaka = 29, Isim = "Gümüşhane" },
            new City { Plaka = 30, Isim = "Hakkari" },
            new City { Plaka = 31, Isim = "Hatay" },
            new City { Plaka = 32, Isim = "Isparta" },
            new City { Plaka = 33, Isim = "Mersin" },
            new City { Plaka = 34, Isim = "İstanbul" },
            new City { Plaka = 35, Isim = "İzmir" },
            new City { Plaka = 36, Isim = "Kars" },
            new City { Plaka = 37, Isim = "Kastamonu" },
            new City { Plaka = 38, Isim = "Kayseri" },
            new City { Plaka = 39, Isim = "Kırklareli" },
            new City { Plaka = 40, Isim = "Kırşehir" },
            new City { Plaka = 41, Isim = "Kocaeli" },
            new City { Plaka = 42, Isim = "Konya" },
            new City { Plaka = 43, Isim = "Kütahya" },
            new City { Plaka = 44, Isim = "Malatya" },
            new City { Plaka = 45, Isim = "Manisa" },
            new City { Plaka = 46, Isim = "Kahramanmaraş" },
            new City { Plaka = 47, Isim = "Mardin" },
            new City { Plaka = 48, Isim = "Muğla" },
            new City { Plaka = 49, Isim = "Muş" },
            new City { Plaka = 50, Isim = "Nevşehir" },
            new City { Plaka = 51, Isim = "Niğde" },
            new City { Plaka = 52, Isim = "Ordu" },
            new City { Plaka = 53, Isim = "Rize" },
            new City { Plaka = 54, Isim = "Sakarya" },
            new City { Plaka = 55, Isim = "Samsun" },
            new City { Plaka = 56, Isim = "Siirt" },
            new City { Plaka = 57, Isim = "Sinop" },
            new City { Plaka = 58, Isim = "Sivas" },
            new City { Plaka = 59, Isim = "Tekirdağ" },
            new City { Plaka = 60, Isim = "Tokat" },
            new City { Plaka = 61, Isim = "Trabzon" },
            new City { Plaka = 62, Isim = "Tunceli" },
            new City { Plaka = 63, Isim = "Şanlıurfa" },
            new City { Plaka = 64, Isim = "Uşak" },
            new City { Plaka = 65, Isim = "Van" },
            new City { Plaka = 66, Isim = "Yozgat" },
            new City { Plaka = 67, Isim = "Zonguldak" },
            new City { Plaka = 68, Isim = "Aksaray" },
            new City { Plaka = 69, Isim = "Bayburt" },
            new City { Plaka = 70, Isim = "Karaman" },
            new City { Plaka = 71, Isim = "Kırıkkale" },
            new City { Plaka = 72, Isim = "Batman" },
            new City { Plaka = 73, Isim = "Şırnak" },
            new City { Plaka = 74, Isim = "Bartın" },
            new City { Plaka = 75, Isim = "Ardahan" },
            new City { Plaka = 76, Isim = "Iğdır" },
            new City { Plaka = 77, Isim = "Yalova" },
            new City { Plaka = 78, Isim = "Karabük" },
            new City { Plaka = 79, Isim = "Kilis" },
            new City { Plaka = 80, Isim = "Osmaniye" },
            new City { Plaka = 81, Isim = "Düzce" },

            new City { Plaka = 1, Isim = "ADANA" },
new City { Plaka = 2, Isim = "ADIYAMAN" },
new City { Plaka = 3, Isim = "AFYONKARAHİSAR" },
new City { Plaka = 4, Isim = "AĞRI" },
new City { Plaka = 5, Isim = "AMASYA" },
new City { Plaka = 6, Isim = "ANKARA" },
new City { Plaka = 7, Isim = "ANTALYA" },
new City { Plaka = 8, Isim = "ARTVİN" },
new City { Plaka = 9, Isim = "AYDIN" },
new City { Plaka = 10, Isim = "BALIKESİR" },
new City { Plaka = 11, Isim = "BİLECİK" },
new City { Plaka = 12, Isim = "BİNGÖL" },
new City { Plaka = 13, Isim = "BİTLİS" },
new City { Plaka = 14, Isim = "BOLU" },
new City { Plaka = 15, Isim = "BURDUR" },
new City { Plaka = 16, Isim = "BURSA" },
new City { Plaka = 17, Isim = "ÇANAKKALE" },
new City { Plaka = 18, Isim = "ÇANKIRI" },
new City { Plaka = 19, Isim = "ÇORUM" },
new City { Plaka = 20, Isim = "DENİZLİ" },
new City { Plaka = 21, Isim = "DİYARBAKIR" },
new City { Plaka = 22, Isim = "EDİRNE" },
new City { Plaka = 23, Isim = "ELAZIĞ" },
new City { Plaka = 24, Isim = "ERZİNCAN" },
new City { Plaka = 25, Isim = "ERZURUM" },
new City { Plaka = 26, Isim = "ESKİŞEHİR" },
new City { Plaka = 27, Isim = "GAZİANTEP" },
new City { Plaka = 28, Isim = "GİRESUN" },
new City { Plaka = 29, Isim = "GÜMÜŞHANE" },
new City { Plaka = 30, Isim = "HAKKARİ" },
new City { Plaka = 31, Isim = "HATAY" },
new City { Plaka = 32, Isim = "ISPARTA" },
new City { Plaka = 33, Isim = "MERSİN" },
new City { Plaka = 34, Isim = "İSTANBUL" },
new City { Plaka = 35, Isim = "İZMİR" },
new City { Plaka = 36, Isim = "KARS" },
new City { Plaka = 37, Isim = "KASTAMONU" },
new City { Plaka = 38, Isim = "KAYSERİ" },
new City { Plaka = 39, Isim = "KIRKLARELİ" },
new City { Plaka = 40, Isim = "KIRŞEHİR" },
new City { Plaka = 41, Isim = "KOCAELİ" },
new City { Plaka = 42, Isim = "KONYA" },
new City { Plaka = 43, Isim = "KÜTAHYA" },
new City { Plaka = 44, Isim = "MALATYA" },
new City { Plaka = 45, Isim = "MANİSA" },
new City { Plaka = 46, Isim = "KAHRAMANMARAŞ" },
new City { Plaka = 47, Isim = "MARDİN" },
new City { Plaka = 48, Isim = "MUĞLA" },
new City { Plaka = 49, Isim = "MUŞ" },
new City { Plaka = 50, Isim = "NEVŞEHİR" },
new City { Plaka = 51, Isim = "NİĞDE" },
new City { Plaka = 52, Isim = "ORDU" },
new City { Plaka = 53, Isim = "RİZE" },
new City { Plaka = 54, Isim = "SAKARYA" },
new City { Plaka = 55, Isim = "SAMSUN" },
new City { Plaka = 56, Isim = "SİİRT" },
new City { Plaka = 57, Isim = "SİNOP" },
new City { Plaka = 58, Isim = "SİVAS" },
new City { Plaka = 59, Isim = "TEKİRDAĞ" },
new City { Plaka = 60, Isim = "TOKAT" },
new City { Plaka = 61, Isim = "TRABZON" },
new City { Plaka = 62, Isim = "TUNCELİ" },
new City { Plaka = 63, Isim = "ŞANLIURFA" },
new City { Plaka = 64, Isim = "UŞAK" },
new City { Plaka = 65, Isim = "VAN" },
new City { Plaka = 66, Isim = "YOZGAT" },
new City { Plaka = 67, Isim = "ZONGULDAK" },
new City { Plaka = 68, Isim = "AKSARAY" },
new City { Plaka = 69, Isim = "BAYBURT" },
new City { Plaka = 70, Isim = "KARAMAN" },
new City { Plaka = 71, Isim = "KIRIKKALE" },
new City { Plaka = 72, Isim = "BATMAN" },
new City { Plaka = 73, Isim = "ŞIRNAK" },
new City { Plaka = 74, Isim = "BARTIN" },
new City { Plaka = 75, Isim = "ARDAHAN" },
new City { Plaka = 76, Isim = "IĞDIR" },
new City { Plaka = 77, Isim = "YALOVA" },
new City { Plaka = 78, Isim = "KARABÜK" },
new City { Plaka = 79, Isim = "KİLİS" },
new City { Plaka = 80, Isim = "OSMANİYE" },
new City { Plaka = 81, Isim = "DÜZCE" }

        };
            var city = cities.FirstOrDefault(ok => ok.Isim == isim);
            if (city != null)
            {
                return city.Plaka;
            }
            else
            {
                return 0;
            }
        }

    }

    public class City
    {
        public int Plaka { get; set; }
        public string Isim { get; set; }
    }
}
