// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pax360DAL;

#nullable disable

namespace Pax360DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250805075310_ver1")]
    partial class ver1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pax360DAL.Models.Authorizations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Module_DosyaYukleme")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Fiyatlar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_IsEmirleri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Kargo")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Loglar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Malzeme")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_ManuelIsEmri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Partner")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_PropaySatis")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_PropaySatisList")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar_Bolgesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar_Portfoy")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Role")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_SatisZiyaret_Listesi")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Satis_Listesi")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_TaksidePosGiris")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Tatiller")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_TeknisyenAdresleri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Users")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Uygulamalar")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Authorizations");
                });

            modelBuilder.Entity("Pax360DAL.Models.RoleTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Module_DosyaYukleme")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Fiyatlar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_IsEmirleri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Kargo")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Loglar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Malzeme")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_ManuelIsEmri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Partner")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_PropaySatis")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_PropaySatisList")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar_Bolgesel")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Raporlar_Portfoy")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Role")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_SatisZiyaret_Listesi")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Satis_Listesi")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_TaksidePosGiris")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Tatiller")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_TeknisyenAdresleri")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Users")
                        .HasColumnType("bit");

                    b.Property<bool>("Module_Uygulamalar")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RoleTypes");
                });

            modelBuilder.Entity("Pax360DAL.Models.Teams", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Pax360DAL.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("bit");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
